In [3]:
import numpy as np

In [4]:
# 1D
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
# 2D
b = np.array([[1,2,3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Array of zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])